languageCode = "en-us"
title = "Tomás Pinho"
baseurl = "http://www.tomaspinho.com/"
theme = "hugo-freelancer-theme"


[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Tomás Pinho"
    description = "Tomás Pinho is a portuguese SysAdmin/DevOps Engineer interested in scalability and security"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = ""

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        brand = "Tomás Pinho"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "profile.jpg"
        name = "Tomás Pinho"
        subtitle = "SysAdmin/DevOps Engineer"
        description = [
"I am a Computer and Informatics Engineer based in Lisbon, Portugal, tech enthusiast, DIYer, music lover and avid reader.",

"This page serves as my home on the Internet of Things (and people) and contains a professional and somewhat personal profile of myself.",

"Check out my <a href=\"cv-en.pdf\" target=\"_blank\">CV <i class=\"fa fa-file-pdf-o red\"></i></a>"
        ]


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Projects"

        [params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttontext = "Close"

    [params.blog]
        title = "Blog"
        link = "https://blog.tomaspinho.com"

    [params.work]
        title = "Work"

    [params.education]
        title = "Education"

    [params.hobbies]
        title = "Hobbies"

    [params.about]
        title = "About"
        # The about text is splitted into a left and right column
        left = "Freelancer is a free bootstrap theme created by Start Bootstrap. The download includes the complete source files including HTML, CSS, and JavaScript as well as optional LESS stylesheets for easy customization."
        right = "Whether you're a student looking to showcase your work, a professional looking to attract clients, or a graphic artist looking to share your projects, this template is the perfect starting point!"

        [params.about.button]
            text = "Download theme"
            link = "//github.com/digitalcraftsman/hugo-freelancer-theme/archive/master.zip"
            icon = "download"

    [params.footer]
        copyright = "Copyright © Tomás Pinho [2017, +OO]."

        [params.footer.location]
            title = "Contact me"
            # Postal address (add as many lines as necessary)
            address = ["me at tomaspinho dot com"]

        [params.footer.social]
            title = "Other homes"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-github"
                link = "https://github.com/tomaspinho/"

            [[params.footer.social.networks]]
                icon = "fa-linkedin"
                link=  "https://www.linkedin.com/in/tomaspinho/"


        [params.footer.credits]
            title = ""
            text = """
<blockquote>
  <p>Intelligence is the ability to avoid doing work, yet getting the work done.</p>
  <footer>Linus Torvalds</footer>
</blockquote>
"""
